name: Archivator
main: de.noltarium.minecraft.Archivator
author: nolte
version: 1.1.0
commands:
   backup:
      description: Start Backup
      usage: /<command> [world]
      permission: Archivator.backup
      permission-message: You don't have <permission>
   backuplist:
      description: List all existing Backups
      usage: /<command> [world]
      permission: Archivator.backup
      permission-message: You don't have <permission>      