# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  release_create:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: publish
          command: |
            echo "Foba"


  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/buildArtefacts/
            find . -type f -regex ".*/target/.*-shaded.jar" -exec cp {} ~/buildArtefacts/ \;
          when: always
      - store_artifacts:
          path: ~/buildArtefacts


      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

      # test optional goal
      - release_create:
          requires:
            - build
          filters:
            tags:
              only: v.*
