# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

defaults: &defaults
  working_directory: /tmp

aliases:
  # Variables.
  # For YAML support of anchors and references, @see http://blog.daemonl.com/2016/02/yaml.html
  - &container_releasemanager
    docker:
      - image: circleci/golang:1.8

  - &run_task_load_latest_ghrelease
    run: |
      sudo wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O /usr/bin/jq
      sudo chmod +x /usr/bin/jq
      LAST_VERSION="$(curl https://${GITHUB_TOKEN}@api.github.com/repos/nolte/minecraft-plugin-archivator/releases/latest | jq -r '.tag_name' )"
      export LAST_VERSION=$LAST_VERSION


jobs:

  finish-release:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - add_ssh_keys:
          fingerprints:
            - "2a:3b:9b:1d:ff:0c:ce:c3:28:8e:5e:74:07:fa:fe:3c"

      - checkout

      - run: |
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git config --global user.name "$GIT_AUTHOR_NAME"
          mvn -B gitflow:release-finish -DpushRemote=true -DallowSnapshots=true




  start-release:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:

      - attach_workspace:
          at: /tmp/workspace

      - add_ssh_keys:
          fingerprints:
            - "2a:3b:9b:1d:ff:0c:ce:c3:28:8e:5e:74:07:fa:fe:3c"

      - checkout

      - run: |
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git config --global user.name "$GIT_AUTHOR_NAME"
          mvn -B gitflow:release-start -DpushRemote=true -DallowSnapshots=true


  generate-changelog:
    machine: true
    working_directory: /tmp/workspace
    steps:
      - *run_task_load_latest_ghrelease
      - run: |
          echo $LAST_VERSION

          docker run -it --rm -v "$(pwd)":/usr/local/src/your-app ferrarimarco/github-changelog-generator:1.15.0.pre.beta --user nolte --project minecraft-plugin-archivator --token ${GITHUB_TOKEN} --since-tag $LAST_VERSION

      - store_artifacts:
          path: /tmp/workspace

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
              - CHANGELOG.md


  publish-github-release:
    <<: *container_releasemanager
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: "Publish the jar on GitHub"
          command: |
            go get github.com/aktau/github-release
            current_version="$(cat /tmp/workspace/current_version.txt)"
            github-release upload \
              --user ${CIRCLE_PROJECT_USERNAME} \
              --repo ${CIRCLE_PROJECT_REPONAME} \
              --tag "${current_version}" \
              --name "minecraft-archivator-v${current_version}.jar" \
              --file /tmp/workspace/buildArtefacts/minecraft-backup-archiver-${current_version}-shaded.jar

  releaseplayground:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/aktau/github-release
            ls -all /tmp/workspace
            message="$(cat /tmp/workspace/CHANGELOG.md)"
            current_version="$(cat /tmp/workspace/current_version.txt)"

            github-release release \
              --user ${CIRCLE_PROJECT_USERNAME} \
              --repo ${CIRCLE_PROJECT_REPONAME} \
              --name "v${current_version}" \
              --description "${message}" \
              --tag "${current_version}" \
              --draft


  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test

      - run: |
          MVN_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          mkdir -p /tmp/workspace/
          echo $MVN_VERSION > /tmp/workspace/current_version.txt


      - run:
          name: Save test results
          command: |
            mkdir -p /tmp/workspace/buildArtefacts/
            find . -type f -regex ".*/target/.*-shaded.jar" -exec cp {} /tmp/workspace/buildArtefacts/ \;
          when: always

      - store_artifacts:
          path: /tmp/workspace/buildArtefacts

      - store_artifacts:
          path: /tmp/workspace/current_version.txt

      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: /tmp/workspace
          # Must be relative path from root
          paths:
              - buildArtefacts
              - current_version.txt


      - run:
          name: Save test results
          command: |
            mkdir -p /tmp/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} /tmp/junit/ \;
          when: always
      - store_test_results:
          path: /tmp/junit

workflows:
  version: 2
#  staticfilesgeneration:
#    jobs:
#      - generate-changelog
#
  development-build:
    jobs:

      - generate-changelog:
          filters:
            branches:
              only: /develop/

      - build:
          filters:
            branches:
              only: /develop/

      - hold:
          type: approval
          requires:
            - build

      - start-release:
          requires:
            - hold



  release-build:
    jobs:

      - build:
          filters:
            branches:
              only: /release.*/

      - generate-changelog:
          filters:
            branches:
              only: /release.*/

      - releaseplayground:
          requires:
            - generate-changelog
            - build

      - publish-github-release:
          requires:
            - releaseplayground

      - finish-release:
          requires:
            - publish-github-release

  release-finished-build:
    jobs:
      - build:
          filters:
            branches:
              only: /master/

#  build-deploy:
#    jobs:
#      - generate-changelog:
#          filters:
#            tags:
#              only: /.*/
#      - build:
#          filters:
#            tags:
#              only: /.*/
#      - publish-github-release:
#          requires:
#            - build
#            - generate-changelog
#          filters:
#            tags:
#              only: /^v.*/
#            branches:
#              ignore: /.*/
