archivator:
  archive:
    dir: archive
    name: mc-{0,DATE,YYYMMDDHHmmSSsss}
    format: zip
  workingtmp: workdir
  strategy: safty
  maxBackupsBeforeErase: 5
  autobackup:
    enabled: false
    intervall: null
  report:
    enabled: true
  sources:
    worlds: '*'
  database:
    type: sqlite
    file: archivator.db
    table_prefix: arc_
  publisher:
    privateftp:
      type: ftp
      host: fofa.ftp.de
      port: 21
      user: exampleuser
      password: password